packages:
  - '.'
  - 'server'
overrides:
  vite: 6.3.5
  '@types/react': 18.3.31
  '@types/react-dom': 18.3.7
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
allowBuilds:
  '@tailwindcss/oxide': false
  esbuild: false
